name: Create Renovate Data

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * *"

permissions:
  contents: read

jobs:
   
  update:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Use node 20
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
          
      - name: Download recent extensions
        run: |
          .\01-update-extension-cache.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        shell: pwsh 
        
      - name: Generate azure-pipelines-marketplace-tasks.json
        run: |
          .\02-generate-renovate-data-marketplace.ps1
        shell: pwsh 

      - name: Generate azure-pipelines-builtin-tasks.json
        run: |
          .\03-generate-renovate-data-builtin.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_ORG: ${{ vars.AZURE_DEVOPS_ORG }}
        shell: pwsh
